# 开发环境配置
# 服务端口
server:
  port: 5000
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    #    url: jdbc:p6spy:mysql://www.ghcbx.cn:13306/jianzhang?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    url: jdbc:p6spy:mysql://127.0.0.1:3306/jianzhang?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    username: root
    password: 123456
    #    password: 888666312
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          log-slow-sql: true

  #配置redis
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 0 # 连接池中的最小空闲连接 默认 0
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

wechat:
  appId: wxfd0657e284654dd3
  appSecret: debaa9c4100f19e5450f0cb30e3c89a8
liteflow:
  rule-source: config/flow.el.xml
wxcorn: 0 5 0/1 * * ?